apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pywxibnse-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pywxibnse-go 
  name: pywxibnse-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pywxibnse-go 
